receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  otlp/logs:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4327

exporters:
  file:
    path: ./etc/test-logs/otlp-logs.log
    flush_interval: 1
  
  debug:
    verbosity: detailed

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp:
    endpoint: "http://loki:3900/otlp"
    tls:
      insecure: true

processors:
  batch:

extensions:
    health_check:

service:
  pipelines:
    logs:
      receivers: [otlp/logs]
      processors: []
      exporters: [file, otlphttp]
    traces:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/tempo]